### PR TITLE
fix extension mode

### PR DESCRIPTION
**Pull request by zerobikappa**
Fixed extension mode so that user can choose to use this plugin in extension mode or docker mode.

To use extension mode, go to:
Tools > Scripts > Plugin Developer Tools

To use docker mode, go to:
Settings > Dockers > Plugin Developer Tools

### CODE REVIEW

**Comment by KnowZero** [comment]
I haven't looked at the entire code yet since the browser preview isn't working for some reason on my pc, I'll download it and try it over the weekend when I have more time.

But before that, let me confirm a few things. Like what is the intention of the extension mode? From the short code I do see you are putting it in a dialog instead of a docker? Is there any benefit to that considering that dockers can be decoupled into dialogs by dragging them out to float?

Even if such implementation is done, I feel like it would be better as a setting to let the user choose rather than confuse the user on what the difference between the two are.

What may make sense is to register some of the buttons like generating the redownload krita api and etc as actions in the scripting menu, or open up the even viewer and etc. I feel like many don't know they exist when they are small buttons under a tab.

If I am drawing the wrong conclusion based on the small snippet I saw, then I apologize, just want to grasp the general intention first so we are on the same page

**Comment by zerobikappa** [comment]
https://github.com/KnowZero/Krita-PythonPluginDeveloperTools/blob/aed2a21778d7bede229efbb2bd4457628501eb05/plugindevtools/PluginDevTools/PluginDevTools.py#L13-L19
In the original source code, I found you not only added this plugin as a docker but also added it as an extension. And you created an empty action in extensions list without assigning any trigger event to it -- that means when you click "Tools > Scripts > Krita Plugin Developer Tools", nothing will happen. I thought maybe you forgot to complete this part of codes, therefore I created this PR to "fix" it. I am not sure if I am doing the wrong thing but I can share some experience after using this plugin in docker mode and extension mode.

In docker mode, unlike other "small" widget, the Developer Tool docker is so "big" that it is not a good idea to make it float out, because the docker only can show on top of the `Krita` main window. That would make it less convenient to click the component which is behind of the widget, especially for users who only have a small monitor. The best way to use it in docker mode is just embed it at the bottom of the `Krita` main window.

In Extension mode, `Krita` would launch plugin with a standalone window. If I `minimize` the `Krita` main window, the plugin window would still keep on desktop. I can easily `maximize` the plugin window to focus on scripting, or `minimize` it to focus on the main window. I also can use `Alt+Tab` to switch between main window and developer tool.

There must be some users who like to embed it into the main window and some users prefer to use it in a standalone window. So the best solution I thought is to keep both mode at the same time.

**Comment by KnowZero** [comment]
Okay, I see. I added that prior because I wanted to add some functions there, but never got around to doing that. It wasn't exactly meant for running it in extensions mode but that is definitely confusing so something must be done there.

And I can see the benefit of running it inside a dialog as it lets you resize, but it also comes with its own downsides that may need fixing. 

Particularly I found these issues, mostly around "focus":

1) If you have the dialog window selected, you can't do element picker. You have to move to the main window to do it. That will confuse people, so on hotkey it would be necessary to move focus to the main window.

2) With it being its own dialog, if multiple krita instances are open, user won't know which it belong to

3) Highlight Widget position does not work

4) You can keep opening multiple extensions for the same window

Personally though, I still don't think it makes sense to have 2 modes and different ways to get there, so I think a better way about this would be to make it that when the docker is set to float, to convert it into a dialog and then when shrunk convert it back into a docker.

I would also convert scripts->Plugin Developer Tools into a menu item, and add some options like "Open as Docker...", "Open as Floating Dialog..." and add "Download API From KDE Git" and "Export API AutoComplete" in there as well

**Comment by zerobikappa** [comment]
Thank you for your comment. In these days I took a try to deal with some issues.

About issue 2, I checked [Krita User Guide](https://docs.krita.org/en/reference_manual/preferences/general_settings.html) and found that the "Allow only one instance of Krita" option was already deprecated since `version 5.0`. So it is supposed that user can not open more than one instance now.

About issue 4, I added some signals and slots to auto switch between docker and dialog. When you drag and release the docker, if it is not finally docked to top/bottom/left/right, it will automatically switch to a dialog. You can also press the "float" button to change the docker to dialog. When you close the dialog, it will switch back to a docker.

I removed "extension mode" from extension codes, but add some functions to create actions menu. You can ignore these codes because it was still under testing. But if you are interested in it, I recommend you to copy the `PluginDevTools.action` file to proper location then you can press `F12` key to fast show the docker.

About issue 1 and 3 (they should be the same thing), I think it supposed to be a bug in original source code, because when the docker was floating, same issue occurred. Sometime I also encounter issues about "None type error". However, it can work in this situation:
1) Start the plugin in docker mode;
2) Enable "Highlight Widget Position" option;
3) Use "selector" to highlight a widget;
4) Popup the docker;
5) Click other widget in tree view list, then we can see the highlight masker successfully move to other widgets' location.

Would you take a look and find out more details about this issue?

**Comment by KnowZero** [comment]
On issue 2, user can open multiple windows if you go to Window->New Window

Overall, for the focus stuff I meant adding something like this line 1080 in `PluginDevToolsWidget.py` change it to something like this should fix it: (not sure if you want me to push to your pull request or not?)
```python
        class windowFilterClass(QWidget):
            def __init__(self, caller, parent=None):
                super().__init__()
                self.caller = caller

            def eventFilter(self, obj, event):
                etype = event.type()

                if etype == QEvent.HoverMove or (etype == QEvent.KeyPress and event.key() == self.caller.modKey[1]):
                    if etype == QEvent.KeyPress and event.key() == self.caller.modKey[1]:
                        win = QtWidgets.qApp.activeWindow()
                        self.caller.selectorWidget=win.findChild(QWidget, "DevToolsSelectorWidget", Qt.FindDirectChildrenOnly)

                    if QApplication.keyboardModifiers() == self.caller.modKey[0]:
                        win = QtWidgets.qApp.activeWindow()
                        if win.__class__.__name__ == 'PluginDevToolsDialog':
                                win.parentWidget().activateWindow()
                        pos = QCursor.pos()
                        onWidget = QApplication.widgetAt(pos)
                        self.caller.setCurrentSelector(onWidget)
                elif etype == QEvent.KeyRelease and event.key() == self.caller.modKey[1] and self.caller.currentWidget:
                        self.caller.finishedSampling()


                #print (obj, event.type())
                return False
```

On the errors, I'll look into it over the weekend

**Comment by zerobikappa** [comment]
Okey, I see. User can open new windows in this way, that means the docker should have multiple instances. I pushed new patch to fix issue 2.
I will be very appreciated if you could push your changes to my PR to test. That can avoid conflicts between PR and main project. And mainly because I still not quite understand how this function works, so it is better to be handled by yourself.

**Comment by KnowZero** [comment]
Okay, now try using the selector when the dialog is open, it should bring focus to the window without needing to switch

**Comment by zerobikappa** [comment]
Element picker works. But if "Highlight Widget Position" was enable, it does not work.

**Comment by KnowZero** [comment]
Should work now

**Comment by zerobikappa** [comment]
Cool, it works now! If you found no other error after review, you can consider to merge and close this PR.

I have some other ideas, such as preset consoleOutputBrowser.verticalScrollMode to "ScrollPerPixel" for smooth scrolling,  or add ctrl+up/ctrl+down to fast load history command, but these are not important. Just for your information, you can consider to add these features in future.

**Comment by KnowZero** [comment]
Commit has been merged, thanks for your contribution :+1:

**Pull request merged**
